export type ListingHost = {
  initials: string;
  gradient: string;
};

export const LISTING_CARDS = [
  {
    title: "Warehouse",
    distanceMi: 0.8,
    pricePerHour: "$85/hr",
    rating: 4.9,
    reviewCount: 128,
    sqFt: 4200,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Warehouse loft interior",
  },
  {
    title: "Kitchen",
    distanceMi: 1.2,
    pricePerHour: "$42/hr",
    rating: 4.7,
    reviewCount: 86,
    sqFt: 1850,
    hosts: [
      { initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" },
      { initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Kitchen",
  },
  {
    title: "Garden terrace",
    distanceMi: 2.1,
    pricePerHour: "$28/hr",
    rating: 4.8,
    reviewCount: 54,
    sqFt: 960,
    hosts: [{ initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" }],
    image: "/images/courtyard.png",
    alt: "Garden terrace",
  },
] as const;

export const FOURTH_SECTION_BY_SPACE = [
  {
    title: "Open warehouse",
    subtitle: "Locomotion testing",
    pricePerHour: "$72",
    rating: 4.9,
    reviewCount: 112,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Open warehouse floor",
  },
  {
    title: "Kitchen lab",
    subtitle: "Manipulation testing",
    pricePerHour: "$48",
    rating: 4.7,
    reviewCount: 64,
    hosts: [{ initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" }],
    image: "/images/kitchen.png",
    alt: "Kitchen lab",
  },
  {
    title: "Garden terrain",
    subtitle: "Mobility testing",
    pricePerHour: "$34",
    rating: 4.8,
    reviewCount: 41,
    hosts: [
      { initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" },
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
    ],
    image: "/images/courtyard.png",
    alt: "Garden terrain",
  },
] as const;

export const FOURTH_SECTION_BY_PROFESSION = [
  {
    title: "Chef",
    subtitle: "Prep, chop & cook motions",
    pricePerHour: "$58",
    rating: 4.9,
    reviewCount: 112,
    hosts: [{ initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" }],
    image: "/images/kitchen.png",
    alt: "Chef movement capture in kitchen",
  },
  {
    title: "Warehouse picker",
    subtitle: "Pick, pack & lift routines",
    pricePerHour: "$44",
    rating: 4.8,
    reviewCount: 94,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Warehouse picker movement capture",
  },
  {
    title: "Housekeeper",
    subtitle: "Clean, wipe & tidy motions",
    pricePerHour: "$38",
    rating: 4.7,
    reviewCount: 76,
    hosts: [
      { initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" },
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Housekeeper movement capture",
  },
  {
    title: "Barista",
    subtitle: "Espresso & pour routines",
    pricePerHour: "$42",
    rating: 4.8,
    reviewCount: 63,
    hosts: [{ initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" }],
    image: "/images/kitchen.png",
    alt: "Barista movement capture",
  },
  {
    title: "Care aide",
    subtitle: "Lift, transfer & assist",
    pricePerHour: "$52",
    rating: 4.6,
    reviewCount: 48,
    hosts: [
      { initials: "AL", gradient: "135deg, #ffa94d 0%, #fd7e14 100%" },
      { initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Care aide movement capture",
  },
  {
    title: "Factory assembler",
    subtitle: "Repetitive assembly tasks",
    pricePerHour: "$46",
    rating: 4.7,
    reviewCount: 81,
    hosts: [{ initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" }],
    image: "/images/warehouse-1.png",
    alt: "Factory assembler movement capture",
  },
] as const;

export const FOURTH_SECTION_BY_ACTION = [
  {
    title: "Washing dishes",
    subtitle: "Sink scrub & rinse",
    pricePerHour: "$48",
    rating: 4.9,
    reviewCount: 128,
    hosts: [{ initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" }],
    image: "/images/kitchen.png",
    alt: "Washing dishes task environment",
  },
  {
    title: "Folding laundry",
    subtitle: "Closet & drawer tidy",
    pricePerHour: "$36",
    rating: 4.7,
    reviewCount: 72,
    hosts: [
      { initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" },
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Folding laundry task environment",
  },
  {
    title: "Vacuuming",
    subtitle: "Living room floors",
    pricePerHour: "$32",
    rating: 4.8,
    reviewCount: 91,
    hosts: [{ initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" }],
    image: "/images/kitchen.png",
    alt: "Vacuuming task environment",
  },
  {
    title: "Making coffee",
    subtitle: "Morning brew routine",
    pricePerHour: "$40",
    rating: 4.8,
    reviewCount: 86,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Making coffee task environment",
  },
  {
    title: "Loading dishwasher",
    subtitle: "Post-meal cleanup",
    pricePerHour: "$42",
    rating: 4.6,
    reviewCount: 64,
    hosts: [{ initials: "AL", gradient: "135deg, #ffa94d 0%, #fd7e14 100%" }],
    image: "/images/kitchen.png",
    alt: "Loading dishwasher task environment",
  },
  {
    title: "Watering plants",
    subtitle: "Garden & patio care",
    pricePerHour: "$28",
    rating: 4.7,
    reviewCount: 53,
    hosts: [
      { initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" },
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
    ],
    image: "/images/courtyard.png",
    alt: "Watering plants task environment",
  },
] as const;

export const FOURTH_SECTION_BY_AUDIENCE = [
  {
    title: "Robotics teams",
    subtitle: "Locomotion & manipulation",
    pricePerHour: "$68",
    rating: 4.9,
    reviewCount: 142,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Robotics team movement capture",
  },
  {
    title: "ML researchers",
    subtitle: "Real-world task data",
    pricePerHour: "$54",
    rating: 4.8,
    reviewCount: 97,
    hosts: [{ initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" }],
    image: "/images/kitchen.png",
    alt: "ML researcher movement capture",
  },
  {
    title: "Hardware startups",
    subtitle: "Prototype validation",
    pricePerHour: "$62",
    rating: 4.7,
    reviewCount: 58,
    hosts: [
      { initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" },
      { initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Hardware startup movement capture",
  },
  {
    title: "University labs",
    subtitle: "Embodied AI studies",
    pricePerHour: "$46",
    rating: 4.8,
    reviewCount: 73,
    hosts: [{ initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" }],
    image: "/images/courtyard.png",
    alt: "University lab movement capture",
  },
  {
    title: "Foundation models",
    subtitle: "Physical intelligence data",
    pricePerHour: "$76",
    rating: 4.9,
    reviewCount: 118,
    hosts: [
      { initials: "AL", gradient: "135deg, #ffa94d 0%, #fd7e14 100%" },
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Foundation model team movement capture",
  },
] as const;

export const FOURTH_SECTION_BY_PRICE = [
  {
    title: "Garden terrace",
    subtitle: "Mobility testing",
    pricePerHour: "$28",
    rating: 4.8,
    reviewCount: 54,
    hosts: [{ initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" }],
    image: "/images/courtyard.png",
    alt: "Garden terrace",
  },
  {
    title: "Garden terrain",
    subtitle: "Outdoor testing",
    pricePerHour: "$34",
    rating: 4.6,
    reviewCount: 37,
    hosts: [
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
      { initials: "AL", gradient: "135deg, #ffa94d 0%, #fd7e14 100%" },
    ],
    image: "/images/courtyard.png",
    alt: "Garden terrain",
  },
  {
    title: "Kitchen",
    subtitle: "Manipulation testing",
    pricePerHour: "$42",
    rating: 4.7,
    reviewCount: 86,
    hosts: [
      { initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" },
      { initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" },
    ],
    image: "/images/kitchen.png",
    alt: "Kitchen",
  },
  {
    title: "Kitchen lab",
    subtitle: "Lab environment",
    pricePerHour: "$48",
    rating: 4.5,
    reviewCount: 29,
    hosts: [{ initials: "AN", gradient: "135deg, #fcc419 0%, #f59f00 100%" }],
    image: "/images/kitchen.png",
    alt: "Kitchen lab",
  },
  {
    title: "Open warehouse",
    subtitle: "Locomotion testing",
    pricePerHour: "$72",
    rating: 4.9,
    reviewCount: 112,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Open warehouse floor",
  },
] as const;

export const FOURTH_SECTION_BY_BUNDLE = [
  {
    title: "Full terrain pack",
    subtitle: "3 spaces",
    pricePerHour: "$128",
    rating: 4.9,
    reviewCount: 203,
    hosts: [
      { initials: "MR", gradient: "135deg, #5c7cfa 0%, #364fc7 100%" },
      { initials: "KL", gradient: "135deg, #e64980 0%, #c2255c 100%" },
    ],
    image: "/images/warehouse-1.png",
    alt: "Full terrain pack bundle",
    spaces: [
      {
        title: "Warehouse loft",
        pricePerHour: "$85",
        image: "/images/warehouse-1.png",
        alt: "Warehouse loft",
      },
      {
        title: "Kitchen",
        pricePerHour: "$42",
        image: "/images/kitchen.png",
        alt: "Kitchen",
      },
      {
        title: "Garden terrace",
        pricePerHour: "$28",
        image: "/images/courtyard.png",
        alt: "Garden terrace",
      },
    ],
  },
  {
    title: "Indoor lab loop",
    subtitle: "3 spaces",
    pricePerHour: "$112",
    rating: 4.7,
    reviewCount: 91,
    hosts: [{ initials: "JS", gradient: "135deg, #38d9a9 0%, #12b886 100%" }],
    image: "/images/kitchen.png",
    alt: "Indoor lab loop bundle",
    spaces: [
      {
        title: "Kitchen lab",
        pricePerHour: "$48",
        image: "/images/kitchen.png",
        alt: "Kitchen lab",
      },
      {
        title: "Open warehouse",
        pricePerHour: "$72",
        image: "/images/warehouse-1.png",
        alt: "Open warehouse",
      },
      {
        title: "Kitchen",
        pricePerHour: "$42",
        image: "/images/kitchen.png",
        alt: "Kitchen",
      },
    ],
  },
  {
    title: "Outdoor mobility set",
    subtitle: "3 spaces",
    pricePerHour: "$96",
    rating: 4.8,
    reviewCount: 118,
    hosts: [
      { initials: "DF", gradient: "135deg, #748ffc 0%, #5c7cfa 100%" },
      { initials: "RP", gradient: "135deg, #da77f2 0%, #9c36b5 100%" },
    ],
    image: "/images/courtyard.png",
    alt: "Outdoor mobility set bundle",
    spaces: [
      {
        title: "Garden terrain",
        pricePerHour: "$34",
        image: "/images/courtyard.png",
        alt: "Garden terrain",
      },
      {
        title: "Warehouse loft",
        pricePerHour: "$85",
        image: "/images/warehouse-1.png",
        alt: "Warehouse loft",
      },
      {
        title: "Garden terrace",
        pricePerHour: "$28",
        image: "/images/courtyard.png",
        alt: "Garden terrace",
      },
    ],
  },
] as const;

export const FOURTH_SECTION_BUDGET_MIN = 50;
export const FOURTH_SECTION_BUDGET_MAX = 500;
